### ISSUE TITLE
sprint 40 bug 

### ISSUE THREAD

**Issue by hjliag** [farteryhr/tetr.js#4]
![screen shot 2018-11-16 at 9 17 48 am](https://user-images.githubusercontent.com/18301182/48589900-db5a1600-e980-11e8-9535-dd515c3cdb91.png)

sprint 40 doesn't end

**Comment by Kamjue** [comment]
Are you sure? I'm playing it online and everything's perfect.
How did you made it happen? What were you doing before? Can you cause it to happen again?

**Comment by farteryhr** [comment]
do a complete refresh with ctrl+F5 and try again?
a call site to `checkwin` has changed to another file and since i didn't set up tool chain supporting things like content hash...

**Comment by hjliag** [comment]
complete refresh works! :D thank you
